#!/usr/bin/env python2

import numpy as np
import argparse
import os
import sys

p = argparse.ArgumentParser(description="print list of frame ids with frames lying in specified xy-range.")

p.add_argument(metavar="FRAME_IDS", dest="frame_ids", help="ASCII file with frame ids to filter as column.")
p.add_argument("-p", "--projections", dest="filename_proj", help="ASCII file with projections.")
p.add_argument("-o", dest="filename_out", default=None, help="output file. if not set, write to STDOUT.")

args = p.parse_args()

if args.filename_out:
  fh_out = open(args.filename_out, 'w')
else:
  fh_out = sys.stdout

frame_ids = sorted(list(np.loadtxt(args.frame_ids, dtype=int, usecols=(0,)).T))
n_frame_ids = len(frame_ids)

f=0
for i, frame in enumerate(open(args.filename_proj, 'r')):
  if i == frame_ids[f]:
    fh_out.write(frame)
    f += 1
    if f == n_frame_ids:
      break

