#!/usr/bin/env python2

import json, pickle
import numpy as np
import argparse
import os
from multiprocessing import Pool
from functools import partial

from md_toolkit import generateTempFilename, parmap
import matplotlib.pyplot as plt

#import supervised_clustering_tools

#frameNeighborhood = supervised_clustering_tools.frameNeighborhood
#load = supervised_clustering_tools.load

def clusterCenters(data_file, clusters):
  data = np.loadtxt(data_file)
  clusters = np.array(clusters, dtype=int)
  centers = {}
  for i in set(clusters).difference(set([0])):
    centers[i] = np.sum(data[clusters == i], axis=0) / np.sum(clusters == i)
  return centers



def density(i, data, rad2, n_rows):
  neighbors = {}
  for j in xrange(i+1, n_rows):
    dist = np.dot(data[i], data[j])
    if dist < rad2:
      neighbors[j] = dist
  return (i, neighbors)



def frameNeighborhood(data_file, density_radius):
  data = np.loadtxt(data_file, dtype=float)
  n_rows, n_cols = data.shape

  rad2 = density_radius**2

  f = partial(density, data=data, rad2=rad2, n_rows=n_rows)
  p = Pool()
  nh = p.map(f, xrange(n_rows))
  return nh



def frameDensity(data_file, clusters, density_radius):
  data, cluster_traj = load(data_file, clusters)
  pass


def runHisto2D(data_file, cols, filter_file=None):
  tmp_name = generateTempFilename(ext=".hist2d")
  if filter_file:
    cmd = "frame_filter -p %s %s | histo2d -c %d,%d -b200 -o %s" % (data_file, filter_file, cols[0], cols[1], tmp_name)
    pass
  else:
    cmd = "cat %s | histo2d -c %d,%d -b200 -o %s" % (data_file, cols[0], cols[1], tmp_name)
  os.popen(cmd)
  return tmp_name

p = argparse.ArgumentParser()
p.add_argument("-p", "--proj", dest="projections",
               help="ASCII file with projected dimensions")
p.add_argument("-c", "--config", dest="config", default="supervised_clustering.conf",
               help="config file (default: manual_clustering.conf)")

p.add_argument("--clear-filter", dest="clear_filter", action="store_true",
               help="clear current filter.")
p.add_argument("--save-filter", dest="save_filter", action="store_true",
               help="save current filter, i.e. assign filtered frames to new cluster")

p.add_argument("--filter", dest="filter_frames", default=None,
               help="apply new filter, define columns as comma-separated pair (e.g. '--filter 1,2')")

p.add_argument("--print-clusters", dest="print_clusters", action="store_true",
               help="print list with assigned clusters. first assigned cluster starts with id=1. all frames with id=0 are unassigned.")

p.add_argument("--print-centers", dest="print_centers", action="store_true",
               help="print coordinates of cluster centers.")

p.add_argument("--print-cluster-interpolation", dest="print_cluster_interpolation", action="store_true",
               help="print list with assigned clusters after interpolating all unassigned frames and thus assigning them to selected clusters.")
p.add_argument("--density-radius", dest="density_radius", default=0.5, type=float,
               help="density radius for cluster interpolation. (default: 0.5)")



args = p.parse_args()


# load config
if os.path.isfile(args.config):
  config = json.load(open(args.config, 'r'))
else:
  config = {}


if args.projections:
  config['projections'] = args.projections


if args.filter_frames:
  data_cols = map(int, args.filter_frames.split(','))
  if not len(data_cols) == 2:
    print "error: frame filter must be defined on exactly two comma-separated columns: e.g. --filter 1,2"
    sys.exit()

  # histogram from currently filtered data along given data columns
  if 'cur_filter' in config and not config['cur_filter'] == None:
    filter_filename = generateTempFilename(ext=".filter")
    np.savetxt(filter_filename, np.array(config['cur_filter']), fmt="%d")
    hist_file = runHisto2D(config['projections'], cols=(data_cols[0], data_cols[1]), filter_file=filter_filename)
    os.remove(filter_filename)
  else:
    # there is no active filter: use full data set
    hist_file = runHisto2D(config['projections'], cols=(data_cols[0], data_cols[1]))

  new_filter = generateTempFilename(ext=".filter")

  # call heatmap with histo and frame-filter
  cmd = ("heatmap --xy-ref %s --close-on-select  --on-select "
         "'frame_identifier --x1 #x1 --y1 #y1 "
         "--x2 #x2 --y2 #y2  -c %d,%d -o %s %s' %s") % (
         config['projections'],
         data_cols[0],
         data_cols[1],
         new_filter,
         config['projections'],
         hist_file)
  os.popen(cmd)

  if os.path.isfile(new_filter):
    # match filter-ids to full data set -> config['cur_filter']
    new_filter_data = np.loadtxt(new_filter, dtype=int, usecols=(0,)).tolist()
    if 'cur_filter' in config and not config['cur_filter'] == None:
      config['cur_filter'] = list(set(new_filter_data).intersection(config['cur_filter']))
    else:
      config['cur_filter'] = new_filter_data

  try:
    os.remove(new_filter)
  except: pass

  os.remove(hist_file)


def clear_filter():
  del config['cur_filter']


if args.clear_filter:
  clear_filter()


if args.save_filter:
  if not 'cluster_traj' in config:
    config['cluster_traj'] = np.zeros(np.loadtxt(config['projections']).shape[0], dtype=int).tolist()
  cluster_id = max(set(config['cluster_traj'])) + 1
  for i in config['cur_filter']:
    config['cluster_traj'][i] = cluster_id
  clear_filter()


if args.print_clusters:
  if 'cluster_traj' in config:
    for i in config['cluster_traj']:
      print i


if args.print_centers:
  centers = clusterCenters(config['projections'], config['cluster_traj'])
  for i in centers:
    print str(i) + ": ", centers[i]


if args.print_cluster_interpolation:
  #TODO
  if 'cluster_traj' in config:
    nh = frameNeighborhood(config['projections'], density_radius=args.density_radius)
    pickle.dump(nh, open("interpol_%0.1f.pickle" % args.density_radius, 'w'))


# save config
json.dump(config, open(args.config, 'w'), indent=2)

